name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f mods.txt ]; then pip install -r mods.txt; fi
    
    - name: Run tests
      run: |
        python -m pytest testsuites/ -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t SHAH7DOCKER/gitauto:latest .
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.SHAH7DOCKER }}
        password: ${{ secrets.shah1q2w3e4r5t6y7u}}
    
    - name: Push Docker image
      run: docker push SHAH7DOCKER/gitauto:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server simulation
      run: |
        echo "Deployment would happen here!"
        echo "In a real scenario, we would:"
        echo "1. SSH into a server"
        echo "2. Pull the new Docker image"
        echo "3. Stop the old container"
        echo "4. Start a new container with the updated image"
