name: CI/CD Pipeline

# Trigger this workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  # Step 1: Run tests
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout your code
      - uses: actions/checkout@v3

      # Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: pytest

  # Step 2: Build and push Docker image (runs only if tests pass)
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout code again
      - uses: actions/checkout@v3

      # Log in to Docker Hub using GitHub secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # SHAH7DOCKER
          password: ${{ secrets.DOCKER_PASSWORD }} # shah1q2w3e4r5t6y7u

      # Build Docker image
      - name: Build Docker image
        run: docker build -t shah7docker/gitauto:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push shah7docker/gitauto:latest
